baseURL = "https://edczero.github.io"
defaultContentLanguage = "en"
title = "EDC0"
theme = "dream"

enableGitInfo = true
enableRobotsTXT = true

hasCJKLanguage = true

[services]
[services.disqus]
shortname = "maverickmac"
#[services.googleAnalytics]
#ID = "G-K6V0YY3HWS"

[markup]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false

# [taxonomies]
# category = "categories"
# tag = "tags"
# series = "series"

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

images = ["me/background.jpg"]

author = "edc0"
description = "All things bullet jpurnal, cats, birds and inspirational"
avatar = "me/edc0.jpg"
headerTitle = "EDC0"
motto = "Wondering in the Land of Longspurs"

# footerBottomText = ""

rss = true

utterancesRepo = "edczero/edczero.github.io"

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "edc0@linuxmail.in"

siteStartYear = 2024

favicon = "favicon.ico"

# Syntax highlighting
customSyntaxHighlighting = true

# options
stickyNav = true
reorderNavItems = ["search", "github", "posts", "categories", "tags", "rss"]
collapseNavItems = ["posts", "categories", "tags", "rss"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

[params.social]
twitter = "edczero"

[params.navItems]
github = { href = "https://github.com/edczero", target = "_blank", icon = "logo-github", title = "GitHub" }

[params.advanced]
customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
#jsDate = true
#jsDateFormat = "yyyy年MM月dd日"
# jsDateFormat = "yyyy年MM月dd日，cccc"
